# Definition of QA pipeline at SonarSource
#
# Possible values for SLAVE: "performance" (for perf tests) and "linux" (for linux machines connected to DB services)

TEST:
  - plugin
  - ruling
  - ci

SQ_VERSION: 
  - DOGFOOD
  - LATEST_RELEASE
  - LATEST_RELEASE[6.7]


exclude:
  
  - SLAVE: linux
    TEST: ci

  - SLAVE: windows
    TEST: ruling

  - TEST: plugin
    SLAVE: linux
    SQ_VERSION: LATEST_RELEASE

  - TEST: ruling
    SLAVE: linux
    SQ_VERSION: DOGFOOD

  - TEST: ruling
    SLAVE: linux
    SQ_VERSION: LATEST_RELEASE[6.7]

  - TEST: plugin
    SLAVE: windows
    SQ_VERSION: DOGFOOD

  - TEST: plugin
    SLAVE: windows
    SQ_VERSION: LATEST_RELEASE[6.7]

  - TEST: ci
    SLAVE: windows
    SQ_VERSION: DOGFOOD

  - TEST: ci
    SLAVE: windows
    SQ_VERSION: LATEST_RELEASE[6.7]
