# Definition of QA pipeline at SonarSource
#
# Possible values for SLAVE: "performance" (for perf tests) and "linux" (for linux machines connected to DB services)

TEST:
  - ruling

SQ_VERSION: 
  - DEV


exclude:

#remove all jobs on performance slave

  - SLAVE: performance 
    SQ_VERSION: DEV 
    TEST: ruling

#remove all jobs on windows slave
  - SLAVE: windows 
    SQ_VERSION: DEV 
    TEST: ruling
