# Definition of QA pipeline at SonarSource
#
# Possible values for SLAVE: "performance" (for perf tests) and "linux" (for linux machines connected to DB services)

TEST:
  - plugin
  - ruling

SQ_VERSION: 
  - DEV

exclude:

#remove all jobs on performance slave

  - SLAVE: performance 
    SQ_VERSION: DEV 
    TEST: ruling

  - SLAVE: performance
    SQ_VERSION: DEV 
    TEST: plugin

#remove all jobs on windows slave
  - SLAVE: windows 
    SQ_VERSION: DEV 
    TEST: ruling

  - SLAVE: windows
    SQ_VERSION: DEV 
    TEST: plugin
