# Definition of QA pipeline at SonarSource
#
# Possible values for SLAVE: "performance" (for perf tests) and "linux" (for linux machines connected to DB services)

TEST:
  - plugin
  - ruling
  - performancing
  - ci

SQ_VERSION: 
  - DEV
  - LATEST_RELEASE
  - LATEST_RELEASE[6.7]


exclude:
  - SLAVE: linux
    TEST: performancing

  - SLAVE: linux
    TEST: ci


  - SLAVE: performance
    TEST: plugin

  - SLAVE: performance
    TEST: ruling

  - SLAVE: performance
    TEST: ci


  - SLAVE: windows
    TEST: ruling

  - SLAVE: windows
    TEST: performancing


  - TEST: plugin
    SLAVE: linux
    SQ_VERSION: LATEST_RELEASE

  - TEST: ruling
    SLAVE: linux
    SQ_VERSION: DEV

  - TEST: ruling
    SLAVE: linux
    SQ_VERSION: LATEST_RELEASE[6.7]

  - TEST: performancing
    SLAVE: performance
    SQ_VERSION: DEV

  - TEST: performancing
    SLAVE: performance
    SQ_VERSION: LATEST_RELEASE

  - TEST: plugin
    SLAVE: windows
    SQ_VERSION: DEV

  - TEST: plugin
    SLAVE: windows
    SQ_VERSION: LATEST_RELEASE[6.7]

  - TEST: ci
    SLAVE: windows
    SQ_VERSION: DEV

  - TEST: ci
    SLAVE: windows
    SQ_VERSION: LATEST_RELEASE[6.7]
