language: java
sudo: false

jdk:
  - oraclejdk8

install: true
script: ./travis.sh
env:
  - TEST=ci
  - TEST=ruling
matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
  webhooks:
    - secure: "MkIJ+5kB2WYajjljfM3wLX32JryncADui3mfl80GQMLJcsx7V4K+Brcmla9ZEASI8D4djg4uuvWpWvsArWnGgpXf3JTwINYpZmW6TgnUPd9u5GQkEb4cf2NBhSziujwTPK5wMRZP8CjuOGa4LwqTLxMXymGay8SP/N9xK+FdlTY="
