# copied from
# https://github.com/aws-samples/aws-serverless-vending-machine/blob/b2898f3ac097e91fedfd021c87968c4266800f15/scripts/deployServerlessVendingMachine.yaml#L260
AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: This script implement a vending machine solution, a way to remove the complexity to provisioning infrastructur for teams.

Parameters:
  EmailApprover:
    Type: String
    Description: The email address of the user or team that will approve a product request.
    Default: ''

  EmailCognito:
    Type: String
    Description: The email address of the user that will be created in the Cognito User Pool. Leave empty to skip user creation.
    Default: ''

  EmailNotification:
    Type: String
    Description: The email address of the user or team that will receive notifications.
    Default: ''

  OrganizationId:
    Type: String
    Description: The Organization ID who will access the S3 Bucket with CFN Templates.
    Default: ''

Resources:
#lambdas
  GetDeployDataDynamoSF:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Timeout: 15
      Role: !GetAtt
        - LambdaExecutionRole
        - Arn
      Runtime: nodejs12.x
      Code:
        ZipFile: |
          // 1
          const AWS = require('aws-sdk');
          const dynamo = new AWS.DynamoDB.DocumentClient();
           exports.handler = function(event, context, callback) {
              console.log('Received event:', JSON.stringify(event));
              var data = event.Input;
              var id = data.id
              if (data.productId) {
                  id = data.productId;
              }
              const params = {
                  TableName: "deploy",
                  Key: {
                    "id": id
                  }
                };
              console.log('DATA:', JSON.stringify(data));
              dynamo.get(params, callback);
          };
