name: Releasability status
'on':
  push:
    branches:
      - js-417
jobs:
  update_releasability_status:
    runs-on: ubuntu-latest
    name: Releasability status
    permissions:
      id-token: write
      statuses: write
      contents: read
    steps:
      -   uses: >-
            SonarSource/gh-action_releasability/releasability-status@v2
          with:
            optional_checks: "Jira"
          env:
            GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
