name: Request review

on:
  pull_request:
    types: ["review_requested"]

jobs:
  MoveCardToReview_job:
    name: Move card to review
    runs-on: ubuntu-latest
    # PRs from forks don't have required token authorization
    if: |
        github.event.pull_request.head.repo.full_name == github.repository
        && github.event.review.author_association != 'NONE'
    steps:
      - uses: sonarsource/gh-action-lt-backlog/MoveCardToReview@use-until-merged
        with:
          github-token: ${{secrets.GH_TOKEN}}
          column-id: "14c3336d"     # Kanban "Review in progress" column
          project-number: 8
