name: Submit Review

on:
  pull_request_review:
    types: ["submitted"]

jobs:
  MoveCardToProgress_job:
    name: Move card to progress
    runs-on: ubuntu-latest
    # Single quotes must be used here https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#literals
    # PRs from forks don't have required token authorization
    if: |
        github.event.pull_request.head.repo.full_name == github.repository
        && github.event.review.author_association != 'NONE'
        && github.event.review.state == 'changes_requested'
    steps:
      - uses: sonarsource/gh-action-lt-backlog/MoveCardAfterReviewV2@use-until-merged
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          column-id: "47fc9ee4"     # Kanban "In progress" column
          project-number: 8

  ReviewApproved_job:
    name: Move card to review approved
    runs-on: ubuntu-latest
    if: |
        github.event.pull_request.head.repo.full_name == github.repository
        && github.event.review.author_association != 'NONE'
        && github.event.review.state == 'approved'
    steps:
      - uses: sonarsource/gh-action-lt-backlog/MoveCardAfterReviewV2@use-until-merged
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          column-id: "dd10adad"     # Kanban "Review approved" column
          project-number: 8
