name: 'Typedoc: site for helper function for the bridge'
on:
  push:
    branches:
      - '**'
permissions:
  contents: write
jobs:
  publish-rules-helper-site:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # for vault
    name: Publish typedoc
    env:
      NPM_CONFIG_registry: https://repox.jfrog.io/artifactory/api/npm/npm
      NPM_CONFIG_//repox.jfrog.io/artifactory/api/npm/:_authToken: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer access_token]
      ARTIFACTORY_URL: https://repox.jfrog.io/artifactory
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3
    - name: Get vault secrets
      id: secrets
      uses: SonarSource/vault-action-wrapper@dc8fe04652687f7278f3ecd27905967836bab0eb # tag=2.7.4-1
      with:
        secrets: |
          development/artifactory/token/{REPO_OWNER_NAME_DASH}-private-reader access_token | ARTIFACTORY_ACCESS_TOKEN;
    - name: setup NPM RC
      run: |
        cp .cirrus/npmrc ./.npmrc
    - name: Build typedoc site
      run: |
        npm ci
        npm run td
    - name: Publish typedoc site
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh_pages
        folder: ./typedoc/site
        target-folder: ./typedoc
        commit-message: "Update the bridge helper functions site"
