name: 'Typedoc: site for helper function for the bridge'
on:
  push:
    branches:
      - '**'
permissions:
  contents: write
jobs:
  publish-rules-helper-site:
    runs-on: ubuntu-latest
    name: Publish typedoc
    env:
      ARTIFACTORY_URL: https://repox.jfrog.io/artifactory
      ARTIFACTORY_ACCESS_TOKEN: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3
    - name: Setup Npm
      run: |
        cp .cirrus/npmrc .npmrc
    - name: Build typedoc site
      run: |
        npm ci
        npm run td
    - name: Publish typedoc site
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh_pages
        folder: ./typedoc/site
        target-folder: ./typedoc
        commit-message: "Update the bridge helper functions site"
